services:
  web:
    image: node:20-buster
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./web:/app
    environment:
      - NEXT_PUBLIC_BACKEND_URL=https://localhost.com/api
      - NEXT_PUBLIC_COOKIE_DOMAIN=.localhost.com
    working_dir: /app
    command: bash -c "npm install && npm run dev"