import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  guidanceMenu,
  menu,
  smallMenu,
  boardMenu,
  selectMenu,
  counselingForm,
} from "../menu";
import { cookies } from "next/headers";
import { Language } from "../common/types";
import LoginCompo from "./components/LoginCompo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const language =
    ((await cookies()).get("language")?.value as Language) || Language.korean;
  return (
    <div className="h-screen w-full flex flex-col ">
      <div className="w-full min-h-15 bg-[#0093EE] flex justify-end gap-3 font-bold items-center pr-5">
        <LoginCompo/>
        <Link href={"/japan"}>
          <img src="/images/japan.png" className="w-6 h-4"></img>
        </Link>
        <Link href={"/usa"}>
          <img src="/images/usa.png" className="w-6 h-4"></img>
        </Link>
      </div>
      <div className="w-full min-h-25 bg-[#0072BA] flex items-center pl-5 peer">
        <Link href={"/"} className="w-1/6 flex justify-center items-center">
        <img src="/images/영진로고.png" className="w-15 h-15"></img>
        <h2 className="font-bold text-white w-full whitespace-nowrap">
          영진전문대학교<br></br>
          한국어교육센터
        </h2>
        </Link>
        <div className="w-full h-full flex justify-evenly text-white font-bold items-center relative">
        <div className="w-1/5 flex justify-center cursor-pointer">{menu[language]?.introduce}</div>
          <div className="w-1/5 flex justify-center cursor-pointer">{menu[language]?.curriculum}</div>
          <div className="w-1/5 flex justify-center cursor-pointer">{menu[language]?.application}</div>
          <div className="w-1/5 flex justify-center cursor-pointer">{menu[language]?.schoolLife}</div>
          <div className="w-1/5 flex justify-center cursor-pointer">{menu[language]?.notification}</div>
        </div>
      </div>
      <div
        className="hidden peer-hover:block hover:block w-full min-h-52 z-50 bg-white absolute z-40"
        style={{ top: "86px" }}
      >
        <div className="min-h-52 flex flex-row w-full">
          <div className="ml-5 h-full w-1/6"></div>
          <div className="w-full h-[100%] flex justify-evenly">
            <div className="w-1/5 h-52 flex flex-col items-center">
              <Link href={`/guidance/introduction`} className="p-2 text-sm font-bold">
                {smallMenu[language]?.centerIntro}
              </Link>
              <Link href={"/guidance/directions"}  className="p-2 text-sm font-bold" >
                {smallMenu[language]?.howToGetHere}
              </Link>
              <Link href={"/staff-intro"}  className="p-2 text-sm font-bold" >
                {smallMenu[language]?.staffIntro}
              </Link>
            </div>
            <div className="w-1/5 h-52 flex flex-col items-center">
              <Link href={"/select/korean-curriculum"}  className="p-2 text-sm font-bold">
                {smallMenu[language]?.["korean-curriculum"]}
              </Link>
              <Link href={"/select/open-campus"} className="p-2 text-sm font-bold" >
                {smallMenu[language]?.["open-campus"]}
              </Link>
              <Link href={"/board/review"} className="p-2 text-sm font-bold" >
              {boardMenu[language]?.review}
              </Link>
            </div>
            <div className="w-1/5 h-52 flex flex-col items-center">
              <Link href={"/select/applied-to"} className="p-2 text-sm font-bold">
                {smallMenu[language]?.["applied-to"]}
              </Link>
              <Link href={"/form/counseling"} className="p-2 text-sm font-bold">
                {counselingForm[language]?.["counseling"]}
              </Link>
              <Link href={"/board/application-form"} className="p-2 text-sm font-bold">
                {boardMenu[language]?.["application-form"]}
              </Link>
              <Link href={"/guidance/visa"} className="p-2 text-sm font-bold">
                {guidanceMenu[language]?.visa}
              </Link>
            </div>
            <div className="w-1/5 h-52 flex flex-col items-center">
              <Link href={"/guidance/dormitory"} className="p-2 text-sm font-bold">
                {smallMenu[language]?.dormitory}
              </Link>
              <Link href={"/guidance/facility"} className="p-2 text-sm font-bold">
                {smallMenu[language]?.facility}
              </Link>
              <Link href={"/board/learning-materials"} className="p-2 text-sm font-bold">
                {boardMenu[language]?.["learning-materials"]}
              </Link>
              <Link href={"/guidance/insurance"} className="p-2 text-sm font-bold">
                {guidanceMenu[language]?.insurance}
              </Link>
            </div>
            <div className="w-1/5 h-52 flex flex-col items-center">
              <Link href={"/board/notice"} className="p-2 text-sm font-bold" >
                {boardMenu[language]?.notice}
              </Link>
              <Link href={"/board/news"} className="p-2 text-sm font-bold" >
                {boardMenu[language]?.news}
              </Link>
              <Link href={"/board/faq"} className="p-2 text-sm font-bold" >
                {boardMenu[language]?.faq}
              </Link>
            </div>
          </div>
        </div>
      </div>
      {/*       <img
        src="/images/한국어교육센터 기본배너.png"
        className="w-full h-60 mt-4 flex justify-center items-center"
      ></img> */}
      {children}
    </div>
  );
}